-- Drop tables if they exist to reset the schema
-- This script assumes that the tables and database already exist.

-- Drop tables in reverse order to respect foreign key constraints

-- Drop the relationship table first
DROP TABLE IF EXISTS TESTS_QUESTIONS_RELATIONSHIP;

-- Drop other tables that have foreign key dependencies
DROP TABLE IF EXISTS QUESTION_ANSWERS;

DROP TABLE IF EXISTS QUESTION_OPTIONS;

-- Drop the main tables
DROP TABLE IF EXISTS QUESTIONS;

DROP TABLE IF EXISTS TESTS;

DROP TABLE IF EXISTS CATEGORY;

DROP TABLE IF EXISTS USERS;

-- Create tables with the updated schema

-- Create a table to store questions
CREATE TABLE QUESTIONS (
    QUESTION_ID INT PRIMARY KEY,
    DESCRIPTION TEXT,
    ANSWER_ID INT,
    DIFFICULTY VARCHAR(255),
    SUBJECT VARCHAR(255),
    TYPE VARCHAR(255)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;

-- Create a table to store options for multiple-choice questions
CREATE TABLE QUESTION_OPTIONS (
    OPTION_ID INT PRIMARY KEY,
    QUESTION_ID INT,
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;

-- Create a table to store correct answers for questions
CREATE TABLE QUESTION_ANSWERS (
    ANSWER_ID INT PRIMARY KEY,
    QUESTION_ID INT,
    OPTION_ID INT,
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID),
    FOREIGN KEY (OPTION_ID) REFERENCES QUESTION_OPTIONS(OPTION_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;

-- Create a table to store user information
CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;

-- Create a table to store test information
CREATE TABLE TESTS (
    TEST_ID INT PRIMARY KEY,
    TEST_DATE DATETIME NULL DEFAULT NULL,
    USER_ID INT NULL DEFAULT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;

-- Create a table to store category information
CREATE TABLE CATEGORY (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_DESC VARCHAR(45) NOT NULL
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;

-- Create a table to store relationships between questions, tests, users, and categories
CREATE TABLE TESTS_QUESTIONS_RELATIONSHIP (
    QUESTION_ID INT NOT NULL,
    TEST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (QUESTION_ID, TEST_ID, USER_ID, CATEGORY_ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID),
    FOREIGN KEY (TEST_ID) REFERENCES TESTS(TEST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_0900_AI_CI;